# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Atlas
tagline:          ''
description:      "AI + QR"
url:              https://jonathanjohann.github.io/Research
baseurl:          /Research/

paginate:         5
