# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            JBlog
tagline:          ''
description:      "Jonathan's Research"
url:              https://jonathanjohann.github.io/Research/
baseurl:          /Research/

paginate:         5
