# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Atlas
tagline:          "The question isn't who is going to let me; it's who is going to stop me - *Ayn Rand*"
description:      ''
url:              https://jonathanjohann.github.io/Research
baseurl:          /Research/

paginate:         5
