# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Research
tagline:          ''
description:      'Welcome to my blog.'
url:              https://jonathanjohann.github.io/Research
baseurl:          /Research/

author:
  name:           #'Mark Otto'
  url:            #https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           #https://github.com/poole/hyde
